## ======================================================================
## resources
## ======================================================================

resource_types:
- name: pull-request
  type: registry-image
  source:
    repository: teliaoss/github-pr-resource
    tag: v0.21.0
- name: gcs
  type: registry-image
  source:
    repository: frodenas/gcs-resource

resources:
- name: gpdb_pr
  type: pull-request
  source:
    repository: greenplum-db/gpdb
    base_branch: "main"
    access_token: ((gpdb-git-access-token))
    ignore_paths:
    - gpdb-doc/*
    - README*

- name: gpdb7-rhel8-build
  type: registry-image
  source:
    repository: gcr.io/data-gpdb-private-images/gpdb7-rhel8-build
    tag: latest
    username: _json_key
    password: ((data-gpdb-private-images-container-registry-readonly-service-account-key))

- name: gpdb7-rhel8-test
  type: registry-image
  source:
    repository: gcr.io/data-gpdb-private-images/gpdb7-rhel8-test
    tag: latest
    username: _json_key
    password: ((data-gpdb-private-images-container-registry-readonly-service-account-key))

jobs:
- name: compile_and_test_gpdb
  public: true
  max_in_flight: 10
  plan:
  - in_parallel:
    - get: gpdb_pr
      trigger: true
      version: every
    - get: gpdb7-rhel8-build
    - get: gpdb7-rhel8-test

  - put: gpdb_pr
    params:
      path: gpdb_pr
      status: pending
  - # "do" the remaining steps with these hooks:
    on_failure:
      put: gpdb_pr
      params:
        path: gpdb_pr
        status: failure
    on_success:
      put: report_pr_success
      resource: gpdb_pr
      params:
        path: gpdb_pr
        status: success
    do:
    - task: init gpdb_src  # Fetch tags and submodules, because the PR resource doesn't.
      image: gpdb7-rhel8-build
      config:
        platform: linux
        run:
          path: bash
          args:
          - -c
          - |
            git clone gpdb_pr gpdb_src &&
            cd gpdb_src &&
            git fetch https://github.com/greenplum-db/gpdb.git --tags &&
            git submodule update --init --recursive
        inputs: [{ name: gpdb_pr }]
        outputs: [{ name: gpdb_src }]
    - in_parallel:
      - task: check_format
        file: gpdb_src/concourse/tasks/check_format.yml

      - task: clang_tidy
        input_mapping:
          gpdb_src: gpdb_pr
        file: gpdb_src/concourse/tasks/clang_tidy.yml

    - task: compile_gpdb_rhel8
      file: gpdb_pr/concourse/tasks/compile_gpdb.yml
      image: gpdb7-rhel8-build
      params:
        CONFIGURE_FLAGS: "--enable-cassert --enable-tap-tests --enable-debug-extensions"
        BLD_TARGETS: "clients loaders"
      timeout: 30m

    - in_parallel:
      - task: icw_planner_rhel8
        tags: [icw-rhel8]
        file: gpdb_pr/concourse/tasks/ic_gpdb.yml
        image: gpdb7-rhel8-test
        input_mapping:
          gpdb_src: gpdb_pr
          bin_gpdb: gpdb_artifacts
        params:
          MAKE_TEST_COMMAND: PGOPTIONS='-c optimizer=off' installcheck-world
          TEST_OS: centos
          CONFIGURE_FLAGS: "--enable-cassert --enable-tap-tests"
        timeout: 3h

      - task: icw_gporca_rhel8
        tags: [icw-rhel8]
        file: gpdb_pr/concourse/tasks/ic_gpdb.yml
        image: gpdb7-rhel8-test
        input_mapping:
          gpdb_src: gpdb_pr
          bin_gpdb: gpdb_artifacts
        params:
          MAKE_TEST_COMMAND: PGOPTIONS='-c optimizer=on' installcheck-world
          TEST_OS: centos
          CONFIGURE_FLAGS: "--enable-cassert --enable-tap-tests"
        timeout: 5h

      - task: unit_tests_gporca_rhel8
        file: gpdb_pr/concourse/tasks/unit_tests_gporca.yml
        image: gpdb7-rhel8-build
        input_mapping:
          gpdb_src: gpdb_pr
        timeout: 1h

