---
platform: linux
image_resource:
  type: registry-image

inputs:
- name: gpdb_src
- name: bin_gpdb_rhel8

outputs:
- name: output

params:
  RC_BUILD_TYPE_GCS:

run:
  path: bash
  args:
  - -ec
  - |
    server_version="$(./gpdb_src/getversion --short)"
    cp bin_gpdb_rhel8/bin_gpdb.tar.gz "output/server-build-${server_version}-rhel8_x86_64${RC_BUILD_TYPE_GCS}.tar.gz"
